services:
  web:
    container_name: test_react
    image: nginx:latest
    volumes:
      - ./dist:/usr/share/nginx/html
      - ./nginx/conf:/etc/nginx/conf.d
    ports:
      - "80:80"
    restart: always
